const GAME_START = "GAME_START";
const GAME_EXIT = "GAME_EXIT";

const LEVEL_EVENT = "LEVEL_EVENT";
const LEVEL_START = "LEVEL_START";
const LEVEL_STOP = "LEVEL_STOP";
const LEVEL_LOAD = "LEVEL_LOAD";
const LEVEL_RELOAD = "LEVEL_RELOAD";
const LEVEL_COMPLETE = "LEVEL_COMPLETE";
const LEVEL_FAILED = "LEVEL_FAILED";
const LEVEL_NEXT = "LEVEL_NEXT";
const LEVEL_PREV = "LEVEL_PREV";
const LEVEL_SHOW_PREVIEW = "LEVEL_SHOW_PREVIEW";
const LEVEL_SHOW_LINE_FAILED = "LEVEL_SHOW_LINE_FAILED";

const CIRCLE_ADD = "CIRCLE_ADD";
const CIRCLE_DROP = "CIRCLE_DROP";

const LINE_INPUT = "LINE_INPUT";
const LINE_ADD_POINT = "LINE_ADD_POINT";
const LINE_UPDATED = "LINE_UPDATED";
const LINE_DROP = "LINE_DROP";
const LINE_GO = "LINE_GO";

const WAY_SHOW = "WAY_SHOW";
const WAY_HIDE = "WAY_HIDE";


export {
    GAME_START,
    GAME_EXIT,

    LEVEL_EVENT,
    LEVEL_START,
    LEVEL_STOP,
    LEVEL_LOAD,
    LEVEL_RELOAD,
    LEVEL_COMPLETE,
    LEVEL_FAILED,
    LEVEL_NEXT,
    LEVEL_PREV,
    LEVEL_SHOW_PREVIEW,
    LEVEL_SHOW_LINE_FAILED,

    CIRCLE_ADD,
    CIRCLE_DROP,

    LINE_INPUT,
    LINE_ADD_POINT,
    LINE_UPDATED,
    LINE_DROP,
    LINE_GO,

    WAY_SHOW,
    WAY_HIDE
};